/*
 * MethodGenerator.java
 *
 * Copyright (c) 2007 Operational Dynamics Consulting Pty Ltd
 * 
 * The code in this file, and the library it is a part of, are made available
 * to you by the authors under the terms of the "GNU General Public Licence,
 * version 2" See the LICENCE file for the terms governing usage and
 * redistribution.
 */
package com.operationaldynamics.codegen;

import java.io.PrintStream;

/**
 * 
 * <p>
 * Source .defs data for a constructor is of the following form:
 * 
 * <pre>
 * (define-method set_label
 *   (of-object &quot;GtkButton&quot;)
 *   (c-name &quot;gtk_button_set_label&quot;)
 *   (return-type &quot;none&quot;)
 *   (parameters
 *     '(&quot;const-gchar*&quot; &quot;label&quot;)
 *   )
 * )
 * </pre>
 * 
 * Code generated by this class will be used as:
 * 
 * <pre>
 * public setLabel(String label) {
 *     GtkButton.setLabel(label);
 * }
 * </pre>
 * 
 * in the public API wrapper classes to be written by the bindings hackers.
 * 
 * @author Andrew Cowie
 */
class MethodGenerator extends FunctionGenerator
{

    /**
     * 
     * @param ofObject
     * @param blockName
     * @param gReturnType
     * @param gFunctionName
     * @param gParameters
     *            a reference to self will be inserted at the head of the
     *            supplied parameter list.
     * 
     */
    MethodGenerator(final Thing ofObject, final String blockName, final String gReturnType,
            final String gFunctionName, final String[][] gParameters) {
        super(ofObject, blockName, gReturnType, gFunctionName, prependReferenceToSelf(ofObject,
                gParameters));
    }

    static String[][] prependReferenceToSelf(Thing self, String[][] parameters) {
        String[][] target;

        target = new String[parameters.length + 1][2];
        System.arraycopy(parameters, 0, target, 1, parameters.length);

        target[0][0] = self.gType;
        target[0][1] = "self";

        return target;
    }

    void writeC(PrintStream out) {
        out.println("TODO");
    }
}
